-- 002_enums.sql
-- Sistem genelinde kullanılacak tüm ENUM tiplerini tanımlar.

CREATE TYPE user_type AS ENUM ('ADMIN', 'USER', 'ORACLE');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'BANNED', 'SUSPENDED');
CREATE TYPE kyc_status AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED');

CREATE TYPE content_type AS ENUM ('VIDEO', 'ARTICLE', 'AUDIO', 'PHOTO', 'ANALYSIS', 'NEWS', 'PRODUCT', 'PERSON');
CREATE TYPE content_visibility AS ENUM ('PUBLIC', 'PRIVATE', 'UNLISTED');

CREATE TYPE market_status AS ENUM ('ACTIVE', 'RESOLVED', 'DISPUTED', 'CANCELLED');
CREATE TYPE market_category AS ENUM ('CRYPTO', 'POLITICS', 'ECONOMY', 'SPORTS', 'SCIENCE', 'TECH', 'POP_CULTURE');

CREATE TYPE signal_position_type AS ENUM ('AMPLIFY', 'DAMPEN', 'SPIKE', 'FADE');
CREATE TYPE market_type AS ENUM ('REACH', 'TRUTH', 'VIBE', 'LENS', 'EDGE', 'VERIFY', 'LAUNCH', 'RISE');

CREATE TYPE order_type AS ENUM ('MARKET', 'LIMIT');
CREATE TYPE order_status AS ENUM ('OPEN', 'FILLED', 'PARTIAL', 'CANCELLED');

CREATE TYPE transaction_type AS ENUM ('DEPOSIT', 'WITHDRAWAL', 'TRADE', 'REWARD', 'STAKE');
CREATE TYPE transaction_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED');

CREATE TYPE nft_status AS ENUM ('MINTED', 'LISTED', 'SOLD', 'BURNED');
CREATE TYPE oracle_type AS ENUM ('CHAINLINK', 'COMMUNITY', 'AI');

CREATE TYPE dispute_status AS ENUM ('NONE', 'OPEN', 'VOTING', 'RESOLVED');
CREATE TYPE notification_type AS ENUM ('TRADE_WIN', 'LIKE', 'REWARD', 'MENTION', 'MARKET_RESOLVED', 'SYSTEM_ALERT');

CREATE TYPE report_type AS ENUM ('SPAM', 'INAPPROPRIATE', 'SCAM', 'OTHER');
CREATE TYPE report_status AS ENUM ('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED');
