export const SIGNAL_TYPES = {
  VIDEO: 'REACH',
  ARTICLE: 'TRUTH',
  AUDIO: 'VIBE',
  PHOTO: 'LENS',
  ANALYSIS: 'EDGE',
  NEWS: 'VERIFY',
  PRODUCT: 'LAUNCH',
  PERSON: 'RISE'
};

export const POSITION_TYPES = {
  REACH: ['AMPLIFY', 'DAMPEN', 'SPIKE', 'FADE'],
  TRUTH: ['CONFIRM', 'REFUTE', 'EVOLVE', 'STALE'],
  VIBE: ['RESONATE', 'FADE', 'TREND', 'NICHE'],
  LENS: ['ICONIC', 'FLEETING', 'VIRAL', 'ARCHIVE'],
  EDGE: ['SHARP', 'DULL', 'EARLY', 'LATE'],
  VERIFY: ['CONFIRMED', 'DISPUTED', 'DEVELOPING', 'RETRACTED'],
  LAUNCH: ['BREAKOUT', 'FLOP', 'STEADY', 'PIVOT'],
  RISE: ['ASCEND', 'DESCEND', 'PLATEAU', 'PIVOT']
};

export const ODDS_CONFIG = {
  DEFAULT_AMPLIFY: 2.0,
  DEFAULT_DAMPEN: 2.0,
  DEFAULT_SPIKE: 10.0,
  DEFAULT_FADE: 5.0
};

export const ORACLE_CONFIG = {
  TIMEOUT_SECONDS: 3600,
  MIN_VALIDATORS: 3,
  CONSENSUS_THRESHOLD: 0.66
};
